import type { Metadata } from "next";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import Section from "@/components/Section";
import styles from "./page.module.scss";

export const metadata: Metadata = {
  title: "Privacy Policy | Trenkit",
  description: "Privacy policy and data protection information for Trenkit.",
};

export default function PrivacyPage() {
  return (
    <>
      <Navbar />
      <main className={styles.main}>
        <Section variant="gradient" className={styles.header}>
          <h1 style={{ color: "white" }}>Privacy Policy</h1>
          <p style={{ color: "rgba(255,255,255,0.9)" }}>
            Last updated: January 22, 2026
          </p>
        </Section>

        <Section variant="light" className={styles.content}>
          <div className={styles.policyContent}>
            <h2>1. Introduction</h2>
            <p>
              Trenkit (&quot;Company&quot;, &quot;We&quot; or &quot;Us&quot;)
              operates this website. This page informs you of our policies
              regarding the collection, use, and disclosure of personal data
              when you use our website and the choices you have associated with
              that data.
            </p>

            <h2>2. Interpretation and Definitions</h2>
            <p>
              <strong>Personal Data</strong> means data about a living
              individual who can be identified from those data (or from those
              and other information either in our possession or likely to come
              into our possession).
            </p>
            <p>
              <strong>Usage Data</strong> refers to data collected automatically
              either generated by the use of the Service or from the Service
              infrastructure itself.
            </p>

            <h2>3. Information Collection and Use</h2>
            <p>
              We collect several different types of information for various
              purposes to provide and improve our Service to you.
            </p>

            <h3>Types of Data Collected:</h3>
            <ul>
              <li>
                <strong>Personal Data:</strong> While using our Service, we may
                ask you to provide us with certain personally identifiable
                information that can be used to contact or identify you
                (&quot;Personal Data&quot;). This may include, but is not
                limited to:
                <ul>
                  <li>Email address</li>
                  <li>First name and last name</li>
                  <li>Phone number</li>
                  <li>Address, State, Province, ZIP/Postal code, City</li>
                </ul>
              </li>
              <li>
                <strong>Usage Data:</strong> We may also collect information on
                how the Service is accessed and used (&quot;Usage Data&quot;).
                This may include information such as your computer&apos;s
                Internet Protocol address, browser type, browser version, the
                pages you visit, the time and date of your visit, and other
                diagnostic data.
              </li>
            </ul>

            <h2>4. Use of Data</h2>
            <p>We use the collected data for various purposes:</p>
            <ul>
              <li>To provide and maintain the Service</li>
              <li>To notify you about changes to our Service</li>
              <li>
                To allow you to participate in interactive features of our
                Service when you choose to do so
              </li>
              <li>To provide customer care and support</li>
              <li>
                To gather analysis or valuable information so that we can
                improve the Service
              </li>
              <li>To monitor the usage of the Service</li>
              <li>To detect, prevent and address technical issues</li>
            </ul>

            <h2>5. Security of Data</h2>
            <p>
              The security of your data is important to us, but remember that no
              method of transmission over the Internet or method of electronic
              storage is 100% secure. While we strive to use commercially
              acceptable means to protect your Personal Data, we cannot
              guarantee its absolute security.
            </p>

            <h2>6. Contact Us</h2>
            <p>
              If you have any questions about this Privacy Policy, please
              contact us at:
            </p>
            <ul>
              <li>By email: privacy@trenkit.com</li>
            </ul>
          </div>
        </Section>
      </main>
      <Footer />
    </>
  );
}
